# BaseImage 
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:12

# Install dependencies
RUN apt-get update && \
    apt-get install curl 

# Installing OpenFaas CLI here
RUN cd /tmp && \
    curl -sSL https://cli.openfaas.com | sh


# Running to display version and help info
RUN faas-cli --version && faas-cli --help

WORKDIR /usr/src/app


COPY ./app/ /usr/src/app/



